  language: objective-c
  matrix:
      include:
          - osx_image: xcode7.3
          - osx_image: xcode8
  install:
      - gem install cocoapods --pre
      - brew install jq
      - npm install shelljs -g
      - npm install glob
      - brew install gradle

  before_script:
        - wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
        - tar xzf android-sdk_r24.4.1-linux.tgz
        - export ANDROID_HOME=$PWD/android-sdk-linux
        - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
        - echo "yes" | android update sdk --filter platform-tools,extra-google-m2repository,extra-android-m2repository,build-tools-24.0.3,android-23,android-24,android-25,android-26,extra-android-support --no-ui --all --force
        - rm -rf ~/Library/Developer/Xcode/DerivedData
        - npm install -g cordova
  script:
      - cordova create app
      - cd app
      - cordova platform add android
      - cordova platform add ios
      - cordova plugin add https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push.git
      - cordova build android
